# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Style Manual
description: > # this means to ignore newlines until "baseurl:"
  The 7th edition of the Style Manual.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown

# Sass settings
#sass:
#  add_charset: true
#  sass_dir: _sass
#  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass
  - vendor

# Plugin settings
plugins:
        #- jekyll-feed
    #- jekyll-sitemap
